/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Candle
 */
export interface Candle {
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    datetime: number;
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    open: number;
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    high: number;
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    close: number;
    /**
     * 
     * @type {number}
     * @memberof Candle
     */
    volume?: number;
}

export function CandleFromJSON(json: any): Candle {
    return CandleFromJSONTyped(json, false);
}

export function CandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Candle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datetime': json['datetime'],
        'open': json['open'],
        'high': json['high'],
        'low': json['low'],
        'close': json['close'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
    };
}

export function CandleToJSON(value?: Candle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datetime': value.datetime,
        'open': value.open,
        'high': value.high,
        'low': value.low,
        'close': value.close,
        'volume': value.volume,
    };
}


