/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HChart
 */
export interface HChart {
    /**
     * 
     * @type {string}
     * @memberof HChart
     */
    zoomType?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof HChart
     */
    spacing?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof HChart
     */
    margin?: Array<number> | null;
}

export function HChartFromJSON(json: any): HChart {
    return HChartFromJSONTyped(json, false);
}

export function HChartFromJSONTyped(json: any, ignoreDiscriminator: boolean): HChart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'zoomType': !exists(json, 'zoomType') ? undefined : json['zoomType'],
        'spacing': !exists(json, 'spacing') ? undefined : json['spacing'],
        'margin': !exists(json, 'margin') ? undefined : json['margin'],
    };
}

export function HChartToJSON(value?: HChart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zoomType': value.zoomType,
        'spacing': value.spacing,
        'margin': value.margin,
    };
}


