/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HMarker
 */
export interface HMarker {
    /**
     * 
     * @type {boolean}
     * @memberof HMarker
     */
    enabled?: boolean;
}

export function HMarkerFromJSON(json: any): HMarker {
    return HMarkerFromJSONTyped(json, false);
}

export function HMarkerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HMarker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function HMarkerToJSON(value?: HMarker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}


