/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HNavigator
 */
export interface HNavigator {
    /**
     * 
     * @type {boolean}
     * @memberof HNavigator
     */
    enabled?: boolean;
}

export function HNavigatorFromJSON(json: any): HNavigator {
    return HNavigatorFromJSONTyped(json, false);
}

export function HNavigatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HNavigator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function HNavigatorToJSON(value?: HNavigator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}


