/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HPoint
 */
export interface HPoint {
    /**
     * 
     * @type {number}
     * @memberof HPoint
     */
    xAxis?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HPoint
     */
    yAxis?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HPoint
     */
    x?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HPoint
     */
    y?: number | null;
}

export function HPointFromJSON(json: any): HPoint {
    return HPointFromJSONTyped(json, false);
}

export function HPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): HPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xAxis': !exists(json, 'XAxis') ? undefined : json['XAxis'],
        'yAxis': !exists(json, 'YAxis') ? undefined : json['YAxis'],
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
    };
}

export function HPointToJSON(value?: HPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'XAxis': value.xAxis,
        'YAxis': value.yAxis,
        'x': value.x,
        'y': value.y,
    };
}


