/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HScrollbar
 */
export interface HScrollbar {
    /**
     * 
     * @type {boolean}
     * @memberof HScrollbar
     */
    enabled?: boolean;
}

export function HScrollbarFromJSON(json: any): HScrollbar {
    return HScrollbarFromJSONTyped(json, false);
}

export function HScrollbarFromJSONTyped(json: any, ignoreDiscriminator: boolean): HScrollbar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function HScrollbarToJSON(value?: HScrollbar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}


