/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HMarker,
    HMarkerFromJSON,
    HMarkerFromJSONTyped,
    HMarkerToJSON,
} from './';

/**
 * 
 * @export
 * @interface HSeries
 */
export interface HSeries {
    /**
     * 
     * @type {string}
     * @memberof HSeries
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof HSeries
     */
    name: string;
    /**
     * 
     * @type {HMarker}
     * @memberof HSeries
     */
    marker: HMarker;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof HSeries
     */
    data: Array<Array<number>>;
    /**
     * 
     * @type {boolean}
     * @memberof HSeries
     */
    showInLegend?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HSeries
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HSeries
     */
    dashStyle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof HSeries
     */
    lineWidth?: number | null;
}

export function HSeriesFromJSON(json: any): HSeries {
    return HSeriesFromJSONTyped(json, false);
}

export function HSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HSeries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'marker': HMarkerFromJSON(json['marker']),
        'data': json['data'],
        'showInLegend': !exists(json, 'showInLegend') ? undefined : json['showInLegend'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'dashStyle': !exists(json, 'dashStyle') ? undefined : json['dashStyle'],
        'lineWidth': !exists(json, 'lineWidth') ? undefined : json['lineWidth'],
    };
}

export function HSeriesToJSON(value?: HSeries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'marker': HMarkerToJSON(value.marker),
        'data': value.data,
        'showInLegend': value.showInLegend,
        'color': value.color,
        'dashStyle': value.dashStyle,
        'lineWidth': value.lineWidth,
    };
}


