/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HStyle
 */
export interface HStyle {
    /**
     * 
     * @type {string}
     * @memberof HStyle
     */
    fontFamily?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HStyle
     */
    fontSize?: string | null;
}

export function HStyleFromJSON(json: any): HStyle {
    return HStyleFromJSONTyped(json, false);
}

export function HStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): HStyle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fontFamily': !exists(json, 'fontFamily') ? undefined : json['fontFamily'],
        'fontSize': !exists(json, 'fontSize') ? undefined : json['fontSize'],
    };
}

export function HStyleToJSON(value?: HStyle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fontFamily': value.fontFamily,
        'fontSize': value.fontSize,
    };
}


