/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTitle
 */
export interface HTitle {
    /**
     * 
     * @type {string}
     * @memberof HTitle
     */
    text: string;
}

export function HTitleFromJSON(json: any): HTitle {
    return HTitleFromJSONTyped(json, false);
}

export function HTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTitle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function HTitleToJSON(value?: HTitle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
    };
}


