/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OrderSide {
    Long = 'long',
    Short = 'short'
}

export function OrderSideFromJSON(json: any): OrderSide {
    return OrderSideFromJSONTyped(json, false);
}

export function OrderSideFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSide {
    return json as OrderSide;
}

export function OrderSideToJSON(value?: OrderSide | null): any {
    return value as any;
}

