/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server

import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.Location

object Paths {
    /**
     * 
     * 
     * @param symbol  
     * @param timeframe  
     * @param fromTs filter by timestamp gte (optional)
     * @param toTs filter by timestamp lte (optional)
     */
    @KtorExperimentalLocationsAPI
    @Location("/candles/{timeframe}/{symbol}/") class candlesRead(val symbol: kotlin.String, val timeframe: kotlin.String, val fromTs: kotlin.Long? = null, val toTs: kotlin.Long? = null)

    /**
     * 
     * 
     */
    @KtorExperimentalLocationsAPI
    @Location("/instruments/last-update/") class instrumentsLastUpdateList()

    /**
     * 
     * 
     */
    @KtorExperimentalLocationsAPI
    @Location("/instruments/") class instrumentsList()

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/available-instruments-meta/") class portfoliosAvailableInstrumentsMetaList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/available-tags/") class portfoliosAvailableTagsList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/delete/") class portfoliosDeleteDelete(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/last-updates/") class portfoliosLastUpdatesList(val portfolio: kotlin.String)

    /**
     * 
     * 
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/") class portfoliosList()

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/orders/") class portfoliosOrdersList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/trades/") class portfoliosTradesList(val portfolio: kotlin.String)

}
