/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server

import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.Location

object Paths {
    /**
     * 
     * 
     * @param symbol  
     * @param timeframe  
     * @param fromDate filter by date gte (optional)
     * @param toDate filter by date lte (optional)
     */
    @KtorExperimentalLocationsAPI
    @Location("/candles/{timeframe}/{symbol}/") class candlesRead(val symbol: kotlin.String, val timeframe: kotlin.String, val fromDate: java.time.LocalDate? = null, val toDate: kotlin.String? = null)

    /**
     * 
     * 
     * @param page A page number within the paginated result set. (optional)
     * @param pageSize Number of results to return per page. (optional)
     */
    @KtorExperimentalLocationsAPI
    @Location("/instruments/") class instrumentsList(val page: kotlin.Int? = null, val pageSize: kotlin.Int? = null)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/available-instruments-meta/") class portfoliosAvailableInstrumentsMetaList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/available-tags/") class portfoliosAvailableTagsList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/delete/") class portfoliosDeleteDelete(val portfolio: kotlin.String)

    /**
     * 
     * 
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/") class portfoliosList()

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/orders/") class portfoliosOrdersList(val portfolio: kotlin.String)

    /**
     * 
     * 
     * @param portfolio  
     */
    @KtorExperimentalLocationsAPI
    @Location("/portfolios/{portfolio}/trades/") class portfoliosTradesList(val portfolio: kotlin.String)

}
