/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param status 
 * @param message 
 */

data class AddResponse (
    @JsonProperty("status")
    val status: AddResponse.Status,
    @JsonProperty("message")
    val message: kotlin.String
) {

    /**
    * 
    * Values: ok,error
    */
    
    enum class Status(val value: kotlin.String){
        @JsonProperty(value="ok") ok("ok"),
        @JsonProperty(value="error") error("error");
    }
}

