/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param datetime 
 * @param open 
 * @param high 
 * @param low 
 * @param close 
 * @param volume 
 */

data class Candle (
    @JsonProperty("datetime")
    val datetime: java.time.OffsetDateTime,
    @JsonProperty("open")
    val open: java.math.BigDecimal,
    @JsonProperty("high")
    val high: java.math.BigDecimal,
    @JsonProperty("low")
    val low: java.math.BigDecimal,
    @JsonProperty("close")
    val close: java.math.BigDecimal,
    @JsonProperty("volume")
    val volume: kotlin.Int
)

