/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param name 
 * @param values 
 */

data class DiscreteMeta (
    @JsonProperty("name")
    val name: kotlin.String,
    @JsonProperty("values")
    val values: kotlin.Array<kotlin.String>
)

