/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Symbol

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param count 
 * @param results 
 * @param next 
 * @param previous 
 */

data class InlineResponse200 (
    @JsonProperty("count")
    val count: kotlin.Int,
    @JsonProperty("results")
    val results: kotlin.Array<Symbol>,
    @JsonProperty("next")
    val next: java.net.URI? = null,
    @JsonProperty("previous")
    val previous: java.net.URI? = null
)

