/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param orderId 
 * @param side 
 * @param orderType 
 * @param status 
 * @param qty 
 * @param placeTime 
 * @param updateTime 
 * @param price 
 * @param executionPrice 
 * @param symbol 
 * @param id 
 * @param tradeId 
 * @param discreteTags 
 * @param continuousTags 
 */

data class NewOrder (
    @JsonProperty("order_id")
    val orderId: kotlin.String,
    @JsonProperty("side")
    val side: kotlin.String,
    @JsonProperty("order_type")
    val orderType: kotlin.String,
    @JsonProperty("status")
    val status: kotlin.String,
    @JsonProperty("qty")
    val qty: java.math.BigDecimal,
    @JsonProperty("place_time")
    val placeTime: java.time.OffsetDateTime,
    @JsonProperty("update_time")
    val updateTime: java.time.OffsetDateTime,
    @JsonProperty("price")
    val price: java.math.BigDecimal,
    @JsonProperty("execution_price")
    val executionPrice: java.math.BigDecimal,
    @JsonProperty("symbol")
    val symbol: kotlin.String,
    @JsonProperty("id")
    val id: kotlin.Int? = null,
    @JsonProperty("trade_id")
    val tradeId: kotlin.String? = null,
    @JsonProperty("discrete_tags")
    val discreteTags: kotlin.Any? = null,
    @JsonProperty("continuous_tags")
    val continuousTags: kotlin.Any? = null
)

