/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param name 
 * @param description 
 * @param createdDate 
 * @param benchmark 
 */

data class Portfolio (
    @JsonProperty("name")
    val name: kotlin.String,
    @JsonProperty("description")
    val description: kotlin.String? = null,
    @JsonProperty("created_date")
    val createdDate: java.time.OffsetDateTime? = null,
    @JsonProperty("benchmark")
    val benchmark: kotlin.String? = null
)

