/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.apis

import com.google.gson.Gson
import firelib.core.SourceName
import firelib.core.domain.Interval
import firelib.core.misc.atMoscow
import firelib.core.store.MdStorageImpl
import io.ktor.application.call
import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.get
import io.ktor.response.respondText
import io.ktor.routing.Route

import org.openapitools.server.Paths


import org.openapitools.server.models.Candle

@KtorExperimentalLocationsAPI
fun Route.CandlesApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()



    get<Paths.candlesRead> {  cl: Paths.candlesRead ->


        val storage = MdStorageImpl()

        val dao = storage.md.getDao(SourceName.FINAM, Interval.Min10)


        val ohlcs = dao.queryAll(cl.symbol)


        val candles = ohlcs.map {
            Candle(
                it.endTime.atMoscow(),
                it.open.toBigDecimal(),
                it.high.toBigDecimal(),
                it.low.toBigDecimal(),
                it.close.toBigDecimal(),
                it.volume.toInt()
            )
        }

        val json = gson.toJson(candles)

        call.respondText(json)

        val exampleContentString = """{
              "volume" : 5,
              "datetime" : "2000-01-23T04:56:07.000+00:00",
              "high" : 6.027456183070403,
              "low" : 1.4658129805029452,
              "close" : 5.962133916683182,
              "open" : 0.8008281904610115
            }"""

    }

}
