version: '3.5'
services:
  hiserver1:
    image: "ivanantipin/hiexport:1.1"
    restart: on-failure
    ports:
      - "8001:7801"
    deploy:
      resources:
        limits:
          memory: 1500M
  hiserver2:
    image: "ivanantipin/hiexport:1.1"
    restart: on-failure
    ports:
      - "8002:7801"
    deploy:
      resources:
        limits:
          memory: 1500M

  hiserver3:
    image: "ivanantipin/hiexport:1.1"
    restart: on-failure
    ports:
      - "8003:7801"
    deploy:
      resources:
        limits:
          memory: 1500M
  bot:
    image: "ivanantipin/techbot:${TAG}"
    restart: on-failure
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 2000M
    volumes:
      - /ddisk/globaldatabase:/ddisk/globaldatabase
    depends_on:
      - hiserver1
      - hiserver2
      - hiserver3