version: '3'
services:
  hiserver:
    image: "ivanantipin/hiexport:1.0"
    restart: on-failure
    network_mode: host
  bot:
    image: "ivanantipin/techbot:20201026-techbot1.0"
    restart: on-failure
    network_mode: host
    environment:
      - TELEGRAM_TOKEN=1072760314:AAHEzPEfFsFRiI5t6aNWNJ20jhZzpnb7dlM
    volumes:
      - /ddisk/globaldatabase:/ddisk/globaldatabase
    depends_on:
      - hiserver