/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param status 
 * @param message 
 */
data class AddResponse (
    val status: AddResponse.Status,
    val message: kotlin.String
) 
{
    /**
    * 
    * Values: ok,error
    */
    enum class Status(val value: kotlin.String){
        ok("ok"),
        error("error");
    }
}

