/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param datetime 
 * @param open 
 * @param high 
 * @param low 
 * @param close 
 * @param volume 
 */
data class Candle (
    val datetime: java.time.LocalDateTime,
    val open: java.math.BigDecimal,
    val high: java.math.BigDecimal,
    val low: java.math.BigDecimal,
    val close: java.math.BigDecimal,
    val volume: kotlin.Int
) 

