/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.Symbol

/**
 * 
 * @param count 
 * @param results 
 * @param next 
 * @param previous 
 */
data class InlineResponse200 (
    val count: kotlin.Int,
    val results: kotlin.Array<Symbol>,
    val next: java.net.URI? = null,
    val previous: java.net.URI? = null
) 

