/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param success Request status
 * @param updateTime Update time
 */
data class InlineResponse200 (
    /* Request status */
    val success: kotlin.Boolean? = null,
    /* Update time */
    val updateTime: kotlin.Long? = null
) 

