/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param symbolAndExchange 
 * @param symbol 
 * @param exchange 
 * @param metaDiscrete 
 * @param metaContinuous 
 */
data class Instrument (
    val symbolAndExchange: kotlin.String,
    val symbol: kotlin.String,
    val exchange: kotlin.String,
    val metaDiscrete: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val metaContinuous: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null
) 

