/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param what 
 * @param &#x60;when&#x60; 
 * @param portfolio 
 * @param id 
 */
data class LastUpdate (
    val what: LastUpdate.What,
    val `when`: kotlin.Int,
    val portfolio: kotlin.String,
    val id: kotlin.Int? = null
) 
{
    /**
    * 
    * Values: instruments,trades,orders
    */
    enum class What(val value: kotlin.String){
        instruments("instruments"),
        trades("trades"),
        orders("orders");
    }
}

