/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param identifier 
 * @param symbol 
 * @param exchange 
 * @param metaDiscrete 
 * @param metaContinuous 
 */
data class NewInstrument (
    val identifier: kotlin.String,
    val symbol: kotlin.String,
    val exchange: kotlin.String,
    val metaDiscrete: kotlin.Any? = null,
    val metaContinuous: kotlin.Any? = null
) 

