/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param orderId 
 * @param side 
 * @param orderType 
 * @param status 
 * @param qty 
 * @param placeTime 
 * @param updateTime 
 * @param symbol 
 * @param discreteTags 
 * @param continuousTags 
 * @param tradeId 
 * @param price 
 * @param executionPrice 
 */
data class NewOrder (
    val orderId: kotlin.String,
    val side: NewOrder.Side,
    val orderType: NewOrder.OrderType,
    val status: NewOrder.Status,
    val qty: java.math.BigDecimal,
    val placeTime: kotlin.Long,
    val updateTime: kotlin.Long,
    val symbol: kotlin.String,
    val discreteTags: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val continuousTags: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,
    val tradeId: kotlin.String? = null,
    val price: java.math.BigDecimal? = null,
    val executionPrice: java.math.BigDecimal? = null
) 
{
    /**
    * 
    * Values: long,short
    */
    enum class Side(val value: kotlin.String){
        long("long"),
        short("short");
    }
    /**
    * 
    * Values: limit,market,stop,stopLimit,marketOnClose,marketOnOpen,limitOnClose,limitOnOpen
    */
    enum class OrderType(val value: kotlin.String){
        limit("limit"),
        market("market"),
        stop("stop"),
        stopLimit("stop_limit"),
        marketOnClose("market_on_close"),
        marketOnOpen("market_on_open"),
        limitOnClose("limit_on_close"),
        limitOnOpen("limit_on_open");
    }
    /**
    * 
    * Values: filled,canceled,placed,partialFilled,new,rejected
    */
    enum class Status(val value: kotlin.String){
        filled("filled"),
        canceled("canceled"),
        placed("placed"),
        partialFilled("partial_filled"),
        new("new"),
        rejected("rejected");
    }
}

