/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param discreteTags 
 * @param continuousTags 
 * @param portfolio 
 * @param orderId 
 * @param side 
 * @param orderType 
 * @param status 
 * @param qty 
 * @param placeTime 
 * @param updateTime 
 * @param symbol 
 * @param id 
 * @param tradeId 
 * @param price 
 * @param executionPrice 
 */
data class Order (
    val discreteTags: kotlin.collections.Map<kotlin.String, kotlin.String>,
    val continuousTags: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>,
    val portfolio: kotlin.String,
    val orderId: kotlin.String,
    val side: Order.Side,
    val orderType: Order.OrderType,
    val status: Order.Status,
    val qty: java.math.BigDecimal,
    val placeTime: java.time.LocalDateTime,
    val updateTime: java.time.LocalDateTime,
    val symbol: kotlin.String,
    val id: kotlin.Int? = null,
    val tradeId: kotlin.String? = null,
    val price: java.math.BigDecimal? = null,
    val executionPrice: java.math.BigDecimal? = null
) 
{
    /**
    * 
    * Values: buy,sell
    */
    enum class Side(val value: kotlin.String){
        buy("buy"),
        sell("sell");
    }
    /**
    * 
    * Values: limit,market,stop,stopLimit,marketOnClose,marketOnOpen,limitOnClose,limitOnOpen
    */
    enum class OrderType(val value: kotlin.String){
        limit("limit"),
        market("market"),
        stop("stop"),
        stopLimit("stop_limit"),
        marketOnClose("market_on_close"),
        marketOnOpen("market_on_open"),
        limitOnClose("limit_on_close"),
        limitOnOpen("limit_on_open");
    }
    /**
    * 
    * Values: filled,canceled,placed,partialFilled
    */
    enum class Status(val value: kotlin.String){
        filled("filled"),
        canceled("canceled"),
        placed("placed"),
        partialFilled("partial_filled");
    }
}

