/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param name 
 * @param description 
 * @param createdDate 
 */
data class Portfolio (
    val name: kotlin.String,
    val description: kotlin.String? = null,
    val createdDate: java.time.LocalDateTime? = null
) 

