/**
* API
* UI API
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.ContinuousMeta
import org.openapitools.server.models.DiscreteMeta

/**
 * 
 * @param continuousMetas 
 * @param discreteMetas 
 */
data class TagsMetaSummary (
    val continuousMetas: kotlin.Array<ContinuousMeta>,
    val discreteMetas: kotlin.Array<DiscreteMeta>
) 

